name: Pull Request - Windows
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - release-500hz
    paths-ignore:
      - 'Documentation/**'
      - 'contrib/gentoo/**'
      - 'contrib/rpm/**'

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  windows:
    name: Package Windows
    uses: ./.github/workflows/package-windows.yml
